[package]
name = "tinyhttp"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinyhttp-internal = { path = "../tinyhttp-internal" }
tinyhttp-codegen = { path = "../tinyhttp-codegen" }