name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch tinyhttp-codegen
      run: git clone https://github.com/yourlitdaddy/tinyhttp-codegen ../tinyhttp-codegen
    - name: Fetch tinyhttp-internal
      run: git clone https://github.com/yourlitdaddy/tinyhttp-internal ../tinyhttp-internal
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
